[package]
name = "canopee-tray"
version = "0.1.0"
edition = "2024"

[dependencies]
objc2 = "0.6"
anyhow = "1.0.104"
trayicon = "0.4.1"
bincode = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
objc2-app-kit = { version = "0.3", features = [
    "NSStatusBar",
    "NSStatusItem",
    "NSMenu",
    "NSAppearance",
    "NSMenuItem",
    "NSImage",
    "NSResponder",
    "NSApplication",
    "NSRunningApplication",
    "NSColor",
    "NSBezierPath",
    "NSBitmapImageRep",
    "NSGraphics",
    "NSWindow",
    "NSPanel",
    "NSView",
    "NSControl",
    "NSButton",
    "NSText",
    "NSFont",
    "NSTextField",
    "NSSearchField",
    "NSTabView",
    "NSTabViewItem",
    "NSTableView",
    "NSTableColumn",
    "NSScrollView",
    "NSAlert",
    "NSOpenPanel",
    "NSSavePanel",
] }
objc2-foundation = { version = "0.3", features = [
    "NSData",
    "NSString",
    "NSThread",
    "NSDate",
    "NSTimer",
    "NSArray",
    "NSURL",
    "NSUserNotification",
    "NSDictionary",
    "objc2-core-foundation",
] }
dirs = "5"
canopee-node = { path = "../canopee/crates/canopee-node" }
canopee-protocol = { path = "../canopee/crates/canopee-protocol" }
canopee-storage = { path = "../canopee/crates/canopee-storage" }
canopee-config = { path = "../canopee/crates/canopee-config" }
canopee-identity = { path = "../canopee/crates/canopee-identity" }